- name: Copy the file to /tmp
  template: src=get-public-subnet-id.sh dest=/tmp/get-public-subnet-id.sh mode=0755

- name: Create NAT gateway by executing the script
  shell: sh /tmp/get-public-subnet-id.sh
