- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    #specify cidr_block for the VPC
    cidr_block: 11.0.0.0/16
    region: ap-northeast-1
    #Prefix for Naming
    prefix: dev
    #avalability zones
    az1: ap-northeast-1a
    az2: ap-northeast-1c
  
  tasks:

    - name: create vpc
      ec2_vpc: 
        state: present
        region: "{{ region }}"
        cidr_block: "{{ cidr_block }}"
        resource_tags: '{"Name":"{{ prefix }}_vpc"}'
      
    #Defining public subnets
        subnets:
          - cidr: 11.0.1.0/24
            az: "{{ az1 }}"
            resource_tags: '{"Name":"{{ prefix }}_public_subnet_1"}'
          - cidr: 11.0.10.0/24
            az: "{{ az2 }}"
            resource_tags: '{"Name":"{{ prefix }}_public_subnet_2"}'
       
    #Defining Private subnets
          - cidr: 11.0.20.0/24
            az: "{{ az1 }}"
            resource_tags: '{"Name":"{{ prefix }}_private_subnet_1"}'
          - cidr: 11.0.30.0/24
            az: "{{ az2 }}"
            resource_tags: '{"Name":"{{ prefix }}_private_subnet_2"}'
    #Defining Internet gateways
        internet_gateway: yes
      
    #Defining Public Route Table
        route_tables:
          - subnets: 
              - 11.0.1.0/24
              - 11.0.10.0/24
            routes:
              - dest: 0.0.0.0/0
                gw: igw
            resource_tags: '{"Name":"{{ prefix }}_public_RT"}'
      register: ec2_vpc
    - debug: 
          msg: "items{{ ec2_vpc.items }}"
      with_items: 
        - "{{ ec2_vpc }}"


#Create NatGateway
- name: Create Nat Gateway and allocate new EIP
  ec2_vpc_nat_gateway:
    state: present
      subnet_id: 
         - "{{ item.id }}"
  with_items: 
    - "{{ ec2_vpc.dev_public_subnet_1 }}"    
#
