- name: Copy the file to /tmp
  template: src=get-private-subnet-zone.sh dest=/tmp/get-private-subnet-zone.sh mode=0755

- name: Getting Private subnet zone by executing the script
  shell: sh /tmp/get-private-subnet-zone.sh
