---
#- hosts: localhost
#  connection: local
# gather_facts: true
#  tasks:
- name: Create-Prod-ELB-Security-Group
  ec2_group:
    name: prod_elb-SG
    description: Production ELB security group
    vpc_id: "{{ lookup('file', '/tmp/get-vpc-id.out') }}"
    region: '{{ region }}'
    rules:
      - proto: tcp
        from_port: 80
        to_port:   80
        cidr_ip:   0.0.0.0/0
    rules_egress:
      - proto: all
        cidr_ip: 0.0.0.0/0
  register: elbsg

- name: Tagging_Prod_ELB_Security_Group
  ec2_tag:
    resource: "{{ elbsg.group_id }}"
    region: '{{ region }}'
    tags:
      Name: prod-elb-SG
    state: present

#- name: Create-VPC-RDS-Security-Group
#  ec2_group:
#    name: prod-rds-security-group
#    description: Security group for prod-rds
#    vpc_id: "{{ lookup('file', '/tmp/get-vpc-id.out') }}" 
#    region: '{{ aws_region }}'
#    rules: 
#      - proto: tcp
#        from_port: 3306
#        to_port:   3306
#        group_id: "{{ natsg.group_id }}"
#    rules_egress:
#      - proto:     all
#        cidr_ip:   0.0.0.0/0
#  register: rdssg
# 
#- name: Tagging the RDS security group
#  ec2_tag:
#    resource: "{{ rdssg.group_id }}"
#    region: ap-northeast-1
#    tags:
#      Name: "prod-rds-security-group"
#    state: present
#    
         


