---
- name: Configuring Elastic Load Balancer
  ec2_elb_lb:
    name: prod-elb-asg
    state: present
    region: "{{ region }}"
    cross_az_load_balancing: "yes"
    connection_draining_timeout: 60
    idle_timeout: 300
    subnets: [ "{{ lookup('file', '/tmp/get-public-subnet-id-1.txt.out') }}",
               "{{ lookup('file', '/tmp/get-public-subnet-id-2.txt.out') }}" ]
    security_group_ids: [ "{{ lookup('file', '/tmp/get-elb-security-group-id.txt.out') }}" ]
                          
#    zones: [ "{{ lookup('file', '/tmp/get-public-subnet-zone-1.txt.out') }}", 
#             "{{ lookup('file', '/tmp/get-public-subnet-zone-2.txt.out') }}" ] 
      #- "{{ lookup('file', '/tmp/get-public-subnet-zone-1.txt.out') }}"
      #- "{{ lookup('file', '/tmp/get-public-subnet-zone-2.txt.out') }}"
    listeners:
      - protocol: http # options are http, https, ssl, tcp
        load_balancer_port: 80
        instance_port: 80
        proxy_protocol: true
