---

- name: provisioning RDS 
  hosts: localhost
  gather_facts: true
  pre_tasks: 
    - include_vars: ../../vars/rds_vars.yml
  roles: 
  - get-vpc-id
  - get-private-subnet-zone
  - get-private-subnet-id 
  - get-public-subnet-zone
  - get-public-subnet-id
  - create-db-subnet-group
  - create-vpc-rds-security-group
  - get-rds-security-group-id
  tasks:
    - name: provisioning RDS in Private Subnets
      rds:
        command: create
        instance_name:          "{{rds_instance_name}}"
        db_engine:              "{{rds_db_engine}}"
        size:                   "{{rds_db_size}}"
        instance_type:          "{{rds_instance_size}}"
        username:               "{{rds_db_user_name}}"
        password:               "{{rds_db_password}}"
        tags:
          Name:                 "{{rds_instance_name}}"
        region:                 "{{aws_region}}"
        vpc_security_groups:    "{{ lookup('file', '/tmp/get-rds-security-group-id.txt.out') }}" 
        multi_zone:             no
        wait:                   yes
        wait_timeout:           500
        subnet: sg-db
#          - "{{ lookup('file', '/tmp/get-private-subnet-id-1.txt.out') }}" 
#          - "{{ lookup('file', '/tmp/get-private-subnet-id-2.txt.out') }}"
#        zone:   
#          - "{{ lookup('file', '/tmp/get-private-subnet-zone-1.txt.out') }}" 
#          - "{{ lookup('file', '/tmp/get-private-subnet-zone-2.txt.out') }}"
      register: rdsinfo  
